# Site settings
title: "1001504 / CCO-130"
#email: your-email@domain.com
description: "Redes de Computadores"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://redes.pmatias.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""